### ISSUE TITLE
dependency injection can't be used anywhere?

### ISSUE THREAD

**Issue by AllenVork** [saulmm/Avengers#9]
Hi
From ur code ,i see some class instance still be created by the new key, not injected. I have no idea which class should be injected ,which shouldn't.

```
    mCharacterListAdapter = new AvengersListAdapter(avengers,
        this, mAvengersListPresenter);
```

nice to get ur reply: zhangruofan@meizu.com

**Comment by saulmm** [comment]
Hello Allen

Dependency injection provides different benefits, on of them is that being a third party component responsive to create the dependencies allows you to provide mocks dependencies on testing, which makes testing easier. In this cases I didn't provide any adapter because I didn't needed (by now). 

BTW I'm injecting things like the usecases, repositories, or presenters. Even being really simple are the core logic of the app. So I'm trying to test those classes properly (in progress).

Probably in further refactors will cover that.
